#!/bin/bash

echo ".';'........................................................
............................................................
''''''''''''''''''''''.':lllccllclc,''''''',,,,'............
::::::cloooooooc::::::':0X0O00000dcdOKKKKKKKKKKOl'..........
OOOOOOO00000000OOkxkOO::00OkO00O0l;kXXXXX0kKNXOO0:..........
XKKKKKXXXXXXXXXXkolldk::000OO00OOl;kXXXXXkd0XKxxO;..........
0000000OOOOOOOOOdco:;l':00OOOO00Oc,xXXX0OKXXXXX0x,..........
xxxxxkkxxxxxxxxkkxlcll':0Ok00OkOOl'oKXXkddddxxoll'..........
dddddddololllloddxxxdc.;0K0O0OkO0Ol:ldxO0Okxlc:;............
:::::::;;;;;;;:llcc:cl;':dddoooooool,.....';,...............
,,''''''''''''::,''.':;....................'................
...............,,;;''.......................................
.................''........................................."

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
